Collect sideEffectFlow using repeatOnLifecycle
orbit-mvi/orbit-mvi pull request #48
Opened 2021-06-24 10:04 UTC by mattmook

Fixes #42

2021-06-24 19:19 UTC, Rosomack requested changes

2021-06-24 19:19 UTC, Rosomack commented on orbit-core/README.md
> +    // For Android, use `lifecycleScope.launch` and `.flowWithLifecycle(lifecycle, Lifecycle.State.STARTED)` instead
You need to update the root `README.md` as well, there's an actual ViewModel example there.

2021-06-25 05:40 UTC, mattmook commented on orbit-core/README.md
> +    // For Android, use `lifecycleScope.launch` and `.flowWithLifecycle(lifecycle, Lifecycle.State.STARTED)` instead
I thought I did a couple of files up?

2021-06-25 06:17 UTC, mattmook commented on orbit-core/README.md
> +    // For Android, use `lifecycleScope.launch` and `.flowWithLifecycle(lifecycle, Lifecycle.State.STARTED)` instead
See https://github.com/orbit-mvi/orbit-mvi/blob/9ec51cdfd50dcd08e319d4ae9894a199aeaa81ec/README.md#connect-to-the-viewmodel-in-your-activity-or-fragment

2021-06-25 07:14 UTC, Rosomack approved these changes

2021-06-25 07:14 UTC, merged