Add one-liner to observe in Activity and Fragment
orbit-mvi/orbit-mvi pull request #59
Opened 2021-07-18 07:55 UTC by mattmook

2021-07-20 14:10 UTC, Rosomack requested changes

2021-07-20 14:10 UTC, Rosomack commented on buildSrc/src/main/kotlin/DependencyManagement.kt
> +    const val androidxLifecycles = "2.4.0-alpha02"
Depending on an alpha version is naff and my only concern here

2021-07-20 14:10 UTC, Rosomack commented on orbit-viewmodel/src/main/kotlin/org/orbitmvi/orbit/viewmodel/ContainerHostExtensions.kt
> +}
What happens if this is called multiple times? E.g. someone shoves it into `onResume` ?

2021-07-20 14:10 UTC, Rosomack reviewed
Just a few comments

2021-07-20 14:38 UTC, mattmook commented on orbit-viewmodel/src/main/kotlin/org/orbitmvi/orbit/viewmodel/ContainerHostExtensions.kt
> +}
bad stuff... in future version we can add a lint rule... I have the code for one already saved

2021-07-20 14:41 UTC, mattmook commented on buildSrc/src/main/kotlin/DependencyManagement.kt
> +    const val androidxLifecycles = "2.4.0-alpha02"
yeah I agree

we have two options:
- we just keep the PR open until such a time it is released; with the knowledge there are issues with lifecycle and side effects
- we merge it in as is and make someone else sad

2021-07-26 07:02 UTC, Rosomack commented on buildSrc/src/main/kotlin/DependencyManagement.kt
> +    const val androidxLifecycles = "2.4.0-alpha02"
I think in this instance it's more important to fix lifecycle defects, let's merge.

2021-07-26 07:03 UTC, Rosomack commented on orbit-viewmodel/src/main/kotlin/org/orbitmvi/orbit/viewmodel/ContainerHostExtensions.kt
> +}
OK, it's easy to abuse so we should be extra careful with the advice we give - lint rule would be useful

2021-07-26 07:03 UTC, Rosomack approved these changes

2021-07-26 07:10 UTC, merged