repeatOnSubscription implementation and example
orbit-mvi/orbit-mvi pull request #61
Opened 2021-07-23 21:51 UTC by mattmook

Quick effort to implement repeatOnSubscription functionality, so intents can collect from expensive sources, such as location or bluetooth only when there are active subscribers, from a fragment point of view when viewLifecycleScope is active.

2021-07-23 22:21 UTC, Rosomack commented on orbit-core/src/commonMain/kotlin/org/orbitmvi/orbit/syntax/simple/SimpleSyntaxExtensions.kt
> +                job = if (it) this@coroutineScope.launch { coroutineScope { block() } } else null
This could be neater if we used e.g. `flatMapLatest` like so:

```
containerContext.subscribedCounter.subscribed.flatMapLatest {
	if (it) flow { coroutineScope { block() } } else channelFlow { awaitClose() } 
}.collect()
```

`flatMapLatest` cancels the last flow whenever a value is emitted.
`channelFlow` with `awaitClose` is a flow that never emits and finishes only when cancelled.

Let me know if this works :)

2021-07-23 22:28 UTC, Rosomack commented on orbit-core/src/commonMain/kotlin/org/orbitmvi/orbit/syntax/simple/SimpleSyntaxExtensions.kt
> +    coroutineScope {
We probably can't avoid this can we?

If you had code after the DSL block it'd never get executed (scope needs to finish before coroutine carries on) - but I don't see how this is different from someone writing this by hand - they'd still need to wrap it in a scope.

An option is to use the container's scope instead - but we probably don't want that

2021-07-23 22:28 UTC, Rosomack commented on orbit-core/src/commonMain/kotlin/org/orbitmvi/orbit/internal/repeatonsubscription/SubscribedCounter.kt
> +        mutex.withLock {
what's faster - a mutex or an atomic?

2021-07-23 22:43 UTC, Rosomack commented on orbit-core/src/commonMain/kotlin/org/orbitmvi/orbit/internal/repeatonsubscription/SubscribedCounter.kt
> +                job = newJob
Juggling jobs can be dropped I think. 

Take a look at this:
```
val test = Channel<Boolean>()
test.receiveAsFlow()
    .distinctUntilChanged() // This might not be necessary since we are strict in emitting only when necessary
    .mapLatest {
        if (!it) {
            delay(500) // delay emission of "inactive" event
        }
        it
    }
    .stateIn(scope = scope, SharingStarted.Lazily, initialValue = false)
```

All we need to do now is push subscribed/unsubscribed booleans down this channel. `mapLatest` will cancel the previous delayed "false" value when a "true" appears.

I'd use the container scope for this too.

2021-07-23 22:45 UTC, Rosomack commented on orbit-core/src/commonMain/kotlin/org/orbitmvi/orbit/internal/repeatonsubscription/RefCountFlow.kt
> +    RefCountFlow(subscribedCounter, this)
do we need this class? Could be replaced with 

```
flow {
	try {
        subscribedCounter.increment()
        upStream.collect(collector)
    } finally {
        subscribedCounter.decrement()
    }
}
```

2021-07-24 05:16 UTC, mattmook commented on orbit-core/src/commonMain/kotlin/org/orbitmvi/orbit/internal/repeatonsubscription/SubscribedCounter.kt
> +        mutex.withLock {
In the very first instance I had atomics, However you need the job creation to be wrapped in a mutex anyway so there didn’t seem to be much point having both

2021-07-24 05:19 UTC, mattmook commented on orbit-core/src/commonMain/kotlin/org/orbitmvi/orbit/internal/repeatonsubscription/RefCountFlow.kt
> +    RefCountFlow(subscribedCounter, this)
You can’t do this for stateflow so figured nicer to have the same code for both

2021-07-24 05:25 UTC, mattmook commented on orbit-core/src/commonMain/kotlin/org/orbitmvi/orbit/internal/repeatonsubscription/SubscribedCounter.kt
> +                job = newJob
I like it will make the rest much neater too. Another thing I haven’t done yet is to push the delay into the settings object

2021-07-24 05:46 UTC, mattmook commented on orbit-core/src/commonMain/kotlin/org/orbitmvi/orbit/internal/repeatonsubscription/SubscribedCounter.kt
> +                job = newJob
A thought this won’t emit the current value when collected which is necessary as repeatOnSubscribed can and will be called when the stateflow is already subscribed

2021-07-24 06:46 UTC, Rosomack commented on orbit-core/src/commonMain/kotlin/org/orbitmvi/orbit/syntax/simple/SimpleSyntaxExtensions.kt
> +                job = if (it) this@coroutineScope.launch { coroutineScope { block() } } else null
Actually I think we can simplify this even further

```
containerContext.subscribedCounter.subscribed.mapLatest<Any?> {
	if (it) coroutineScope { block() } else null
}.collect()
```

2021-07-24 06:47 UTC, Rosomack commented on orbit-core/src/commonMain/kotlin/org/orbitmvi/orbit/internal/repeatonsubscription/SubscribedCounter.kt
> +                job = newJob
> A thought this won’t emit the current value when collected which is necessary as repeatOnSubscribed can and will be called when the stateflow is already subscribed

It exposes a stateflow? Through the `stateIn` operator.

2021-07-24 06:53 UTC, mattmook commented on orbit-core/src/commonMain/kotlin/org/orbitmvi/orbit/internal/repeatonsubscription/SubscribedCounter.kt
> +                job = newJob
In the above, I think distinctUntilChanged is necessary but should be after mapLatest... consider sending true, false, true in quick succession, true will be emitted twice

2021-07-24 07:05 UTC, mattmook commented on orbit-core/src/commonMain/kotlin/org/orbitmvi/orbit/syntax/simple/SimpleSyntaxExtensions.kt
> +                job = if (it) this@coroutineScope.launch { coroutineScope { block() } } else null
was just thinking that myself :-)

2021-07-24 07:11 UTC, mattmook commented on orbit-core/src/commonMain/kotlin/org/orbitmvi/orbit/syntax/simple/SimpleSyntaxExtensions.kt
> +    coroutineScope {
no, I think we want it like this

2021-07-24 07:11 UTC, mattmook commented on orbit-core/src/commonMain/kotlin/org/orbitmvi/orbit/internal/repeatonsubscription/SubscribedCounter.kt
> +                job = newJob
haha, yes sorry missed the stateIn bit for some reason

2021-07-24 07:15 UTC, mattmook commented on orbit-core/src/commonMain/kotlin/org/orbitmvi/orbit/internal/repeatonsubscription/SubscribedCounter.kt
> +                job = newJob
```
    private val _subscribed: MutableStateFlow<Boolean> = MutableStateFlow(false)
    public val subscribed: Flow<Boolean> = _subscribed.mapLatest {
        if (!it) {
            delay(repeatOnSubscribedStopTimeout)
        }
        it
    }.distinctUntilChanged()
```

vs

```
    private val _subscribed = Channel<Boolean>()
    public val subscribed: Flow<Boolean> = _subscribed
        .receiveAsFlow()
        .mapLatest {
            if (!it) {
                delay(repeatOnSubscribedStopTimeout)
            }
            it
        }
        .distinctUntilChanged()
        .stateIn(scope = scope, SharingStarted.Lazily, initialValue = false)
```

not really much in it is there??? one is not apologetic for being a state flow up front

2021-07-24 07:32 UTC, mattmook commented on orbit-core/src/commonMain/kotlin/org/orbitmvi/orbit/internal/repeatonsubscription/SubscribedCounter.kt
> +        mutex.withLock {
code now updated

given we query the counter and then post to the stream, I assume we are best surrounding with a mutex... we want to ensure the values are always sent in order inline with the counter changes... if they were to be sent out of order then we could end up with problems

2021-07-27 21:51 UTC, mattmook commented on orbit-core/src/commonTest/kotlin/org/orbitmvi/orbit/internal/repeatonsubscription/DelayingSubscribedCounterTest.kt
> +            assertTrue(testObserver.values.first().time in 450..550)
test is flaky; not sure if its safer to just change this to `assertTrue(testObserver.values.first().time > 450)`

thoughts @Rosomack?

2021-07-27 22:00 UTC, mattmook commented on orbit-core/src/commonMain/kotlin/org/orbitmvi/orbit/syntax/simple/SimpleSyntaxExtensions.kt
> +public suspend fun <S : Any, SE : Any> SimpleSyntax<S, SE>.repeatOnSubscription(
not tested this yet

2021-07-29 05:12 UTC, Rosomack commented on orbit-core/src/commonTest/kotlin/org/orbitmvi/orbit/syntax/simple/SimpleSyntaxExtensionsKtTest.kt
> +internal class SimpleSyntaxExtensionsKtTest {
I got the rest of the simple syntax test under `SimpleDslBehaviourTest`, could we like collect them under one file? Or rename this one to something more `repeatOnSubscription` specific?

2021-07-29 05:15 UTC, Rosomack commented on orbit-core/src/commonMain/kotlin/org/orbitmvi/orbit/internal/repeatonsubscription/DelayingSubscribedCounter.kt
> +            job.lazySet(scope.launch {
why lazySet and not just `job.value =` ?

2021-07-29 05:18 UTC, mattmook commented on orbit-core/src/commonMain/kotlin/org/orbitmvi/orbit/internal/repeatonsubscription/DelayingSubscribedCounter.kt
> +            job.lazySet(scope.launch {
looking at the api it felt more correct as it'll freeze the value of the atomic is frozen before setting, whereas setValue just sets the value 🤷

2021-07-29 05:19 UTC, mattmook commented on orbit-core/src/commonMain/kotlin/org/orbitmvi/orbit/internal/repeatonsubscription/DelayingSubscribedCounter.kt
> +            job.lazySet(scope.launch {
seems to make no difference either way though

2021-07-29 05:20 UTC, mattmook commented on orbit-core/src/commonMain/kotlin/org/orbitmvi/orbit/internal/repeatonsubscription/DelayingSubscribedCounter.kt
> +            job.lazySet(scope.launch {
oh no I tell a lie... does the same... its setValue that doesn't freeze

2021-07-29 05:23 UTC, Rosomack approved these changes

2021-07-29 05:26 UTC, Rosomack requested changes

2021-07-29 05:26 UTC, Rosomack commented on orbit-core/src/commonMain/kotlin/org/orbitmvi/orbit/internal/repeatonsubscription/DelayingSubscribedCounter.kt
> +            job.value = scope.launch {
We should probably cancel the job here as well, otherwise the previous job's `Unsubscribe` might come back to haunt us

2021-07-29 08:12 UTC, Rosomack approved these changes

2021-07-29 08:35 UTC, merged